---
- hosts: dbservers
  become: true
  gather_facts: False
  
  tasks: 
  - name: copying database dump file
    copy: 
      src: files/db_backup.sql
      dest: /root
    tags: 
     - deploy

  - name: restoring database
    mysql_db:
      name: accounts
      login_user: admin
      login_password: admin123
      state: import
      target: /root/db_backup.sql
    tags: 
     - deploy
    notify:
      - Restart mysql

  handlers:
  - name: Restart mysql
    service: 
      name: mysql 
      state: restarted
